# Generated by Django 3.1.7 on 2021-04-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('enrol', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('fees', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('image', models.ImageField(default='user.png', upload_to='upload/')),
            ],
        ),
    ]
