# Generated by Django 3.1.7 on 2021-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('enroll', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
